### ISSUE TITLE
vs code1.53.0 无法使用Luaide

### ISSUE THREAD

**Issue by CodeGize** [hsu2017/luaide-lite#27]
![image](https://user-images.githubusercontent.com/9925061/106999913-04fdf280-67c2-11eb-90ed-b8e5ecdfb6d0.png)
付费版本的所有功能均不可用

**Comment by CodeGize** [comment]
Luaide正式版本

**Comment by hsu2017** [comment]
你好，luaide不是我维护的，建议联系原作者。我维护的是luaide-lite免费版，和luaide已大不一样。
