### ISSUE TITLE
vscode升级到1.33.0后，断点调试会崩溃

### ISSUE THREAD

**Issue by lujun495904500** [hsu2017/luaide-lite#9]
今天把vscode升级到最新的1.33.0版本后，如果在vs中下有断点，程序会直接崩溃。没有断点则正常运行。不知大家遇到这个问题没有

**Comment by HelloWorld886** [comment]
同样遇到问题，先打好断点，再点击调试，会直接shutdown

**Comment by lujun495904500** [comment]
> 同样遇到问题，先打好断点，再点击调试，会直接shutdown

解决了吗，不知道是不是 vscode 再更新就好了

**Comment by HelloWorld886** [comment]
> > 同样遇到问题，先打好断点，再点击调试，会直接shutdown
> 
> 解决了吗，不知道是不是 vscode 再更新就好了

更新了也不行，目前只能先取消断点再点调试

**Comment by lujun495904500** [comment]
更新到 1.33.1 问题解决了
